import streamlit as st
import pandas as pd
import io

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from docx import Document

# ==================================================
# LOGIN CHECK
# ==================================================

if "logged_in" not in st.session_state or not st.session_state.logged_in:
    st.warning("Please login first.")
    st.stop()

st.title("📄 AI Report Generation")

# ==================================================
# SESSION STATE
# ==================================================

df = st.session_state.get("cleaned_df")
best_model_name = st.session_state.get("best_model_name")
problem_type = st.session_state.get("problem_type")
target_column = st.session_state.get("target_column")
results_df = st.session_state.get("results_df")
user_role = st.session_state.get("user_role", "Data Scientist")

if df is None or best_model_name is None or problem_type is None or target_column is None or results_df is None:
    st.error("❌ Report cannot be generated.")
    st.info("Train the model first.")
    st.stop()

st.success("✅ Report Data Loaded")

# ==================================================
# GET BEST MODEL
# ==================================================

best_row = results_df[results_df["Model"] == best_model_name].iloc[0]

train_score = None
val_score = None
test_score = None

if "Train Score" in results_df.columns:
    train_score = best_row["Train Score"]

if "Validation Score" in results_df.columns:
    val_score = best_row["Validation Score"]

if "Test Score" in results_df.columns:
    test_score = best_row["Test Score"]

if val_score is None:

    if "Accuracy" in results_df.columns:
        val_score = best_row["Accuracy"]

    elif "R2 Score" in results_df.columns:
        val_score = best_row["R2 Score"]

# ==================================================
# START REPORT
# ==================================================

report_lines = []

report_lines.append("INSIGHTFLOW AI ANALYSIS REPORT")
report_lines.append("")

report_lines.append("DATASET SUMMARY")
report_lines.append(f"Rows: {df.shape[0]}")
report_lines.append(f"Columns: {df.shape[1]}")
report_lines.append("")

# ==================================================
# EXECUTIVE SUMMARY
# ==================================================

report_lines.append("📊 EXECUTIVE AI SUMMARY")

report_lines.append(
f"The AI system trained multiple models and selected {best_model_name} "
f"as the best performing algorithm for predicting {target_column}."
)

report_lines.append("")

# ==================================================
# MODEL PERFORMANCE
# ==================================================

report_lines.append("MODEL PERFORMANCE")

report_lines.append(f"Problem Type: {problem_type}")
report_lines.append(f"Best Model: {best_model_name}")
report_lines.append(f"Validation Score: {val_score}")

if train_score:
    report_lines.append(f"Train Score: {train_score}")

if test_score:
    report_lines.append(f"Test Score: {test_score}")

report_lines.append("")

# ==================================================
# MODEL EXPLAINABILITY
# ==================================================

report_lines.append("🧠 MODEL EXPLAINABILITY")

report_lines.append(
"The model identifies patterns in the dataset to predict the target variable. "
"Feature relationships influence the final predictions generated by the AI system."
)

report_lines.append("")

# ==================================================
# PREDICTION CONFIDENCE
# ==================================================

report_lines.append("📉 PREDICTION CONFIDENCE")

if val_score > 0.9:
    confidence = "Very High"
elif val_score > 0.75:
    confidence = "High"
elif val_score > 0.6:
    confidence = "Moderate"
else:
    confidence = "Low"

report_lines.append(f"Prediction Confidence Level: {confidence}")
report_lines.append("")

# ==================================================
# ROLE BASED INSIGHTS
# ==================================================

# -----------------------------
# DATA SCIENTIST REPORT
# -----------------------------

if user_role == "Data Scientist":

    report_lines.append("TECHNICAL MODEL INSIGHTS")

    gap = 0
    if train_score and val_score:
        gap = train_score - val_score

    report_lines.append(f"Train Validation Gap: {round(gap,4)}")

    if gap > 0.1:
        report_lines.append("Potential overfitting detected.")
    else:
        report_lines.append("Model generalization is stable.")

    report_lines.append("")

# -----------------------------
# DATA ANALYST REPORT
# -----------------------------

elif user_role == "Data Analyst":

    report_lines.append("📊 DATA PATTERN INSIGHTS")

    numeric_cols = df.select_dtypes(include="number").columns

    for col in numeric_cols[:3]:
        report_lines.append(
            f"{col} average value: {round(df[col].mean(),2)}"
        )

    report_lines.append("")

# -----------------------------
# NON TECHNICAL REPORT
# -----------------------------

elif user_role == "Non-Technical User":

    report_lines.append("AI INTERPRETATION")

    report_lines.append(
        "The AI system analyzes historical data to generate reliable predictions "
        "that can support business decisions."
    )

    report_lines.append("")

# -----------------------------
# BUSINESS REPORT
# -----------------------------

elif user_role == "Business User":

    report_lines.append("📈 BUSINESS KPI INSIGHTS")

    numeric_cols = df.select_dtypes(include="number").columns

    if len(numeric_cols) > 0:

        for col in numeric_cols[:2]:
            total = df[col].sum()
            report_lines.append(f"Total {col}: {round(total,2)}")

    report_lines.append("")

# ==================================================
# AI RECOMMENDATIONS
# ==================================================

report_lines.append("🤖 AI RECOMMENDATIONS")

if val_score > 0.9:
    report_lines.append(
        "The model is highly reliable and can be used for production deployment."
    )
elif val_score > 0.75:
    report_lines.append(
        "Model performance is strong. Minor hyperparameter tuning may improve accuracy."
    )
else:
    report_lines.append(
        "Additional feature engineering and model tuning is recommended."
    )

report_lines.append("")

# ==================================================
# MODEL LEADERBOARD
# ==================================================

report_lines.append("MODEL COMPARISON")

for _, row in results_df.iterrows():

    train = row["Train Score"] if "Train Score" in results_df.columns else "-"
    val = row["Validation Score"] if "Validation Score" in results_df.columns else "-"

    if val == "-" and "Accuracy" in results_df.columns:
        val = row["Accuracy"]

    if val == "-" and "R2 Score" in results_df.columns:
        val = row["R2 Score"]

    report_lines.append(f"{row['Model']} | Score: {val}")

report_lines.append("")

# ==================================================
# PREVIEW
# ==================================================

st.subheader("📋 Report Preview")

for line in report_lines:
    st.write(line)

# ==================================================
# DOWNLOAD OPTIONS
# ==================================================

download_type = st.selectbox("Download Format", ["PDF","Word"])

# ==================================================
# PDF REPORT
# ==================================================

if download_type == "PDF":

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer)

    elements = []
    styles = getSampleStyleSheet()

    for line in report_lines:
        elements.append(Paragraph(line, styles["Normal"]))
        elements.append(Spacer(1,0.2*inch))

    doc.build(elements)

    st.download_button(
        "📥 Download Professional PDF Report",
        buffer.getvalue(),
        "InsightFlow_AI_Report.pdf",
        "application/pdf"
    )

# ==================================================
# WORD REPORT
# ==================================================

else:

    doc = Document()

    for line in report_lines:
        doc.add_paragraph(line)

    buffer = io.BytesIO()
    doc.save(buffer)

    st.download_button(
        "📥 Download Word Report",
        buffer.getvalue(),
        "InsightFlow_AI_Report.docx",
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )